export 'onboarding.dart';
export 'auth.dart';
export 'home.dart';
export 'aboutUs.dart';
export 'details.dart';
export 'treatments.dart';
export 'treatment-detail.dart';
export 'appointments.dart';
export 'settings.dart';